apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sandstonemerchant-com-tls
spec:
  secretName: sandstonemerchant-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sandstonemerchant.com
  dnsNames:
    - sandstonemerchant.com
    - www.sandstonemerchant.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sandstonemerchant.com
          - www.sandstonemerchant.com